# Generated by Django 4.2.3 on 2023-11-03 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('research_title', models.CharField(max_length=200)),
                ('area_of_research', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('guide', models.CharField(max_length=100)),
                ('co_guide', models.CharField(max_length=100)),
                ('register_as', models.CharField(choices=[('Residential', 'Residential'), ('Non-Residential', 'Non-Residential')], max_length=20)),
                ('register_on', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('dob', models.DateField()),
                ('lives_in', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Homepage.student_cards')),
            ],
        ),
    ]
