# Generated by Django 4.2.3 on 2023-11-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0003_studentdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='co_guide',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
