# Generated by Django 4.2.3 on 2023-11-03 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0004_alter_studentdetails_co_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressSeminarReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('supervisor_name', models.CharField(max_length=100)),
                ('topic_approval_seminar', models.CharField(max_length=20)),
                ('sps_01', models.CharField(max_length=20)),
                ('aps_01', models.CharField(max_length=20)),
                ('sps_02', models.CharField(max_length=20)),
                ('aps_02', models.CharField(max_length=20)),
                ('sps_03', models.CharField(max_length=20)),
                ('aps_03', models.CharField(max_length=20)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Homepage.student_cards')),
            ],
        ),
    ]
