# Generated by Django 4.2.3 on 2023-11-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0006_studentmasterlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmasterlist',
            name='student',
        ),
        migrations.AddField(
            model_name='studentmasterlist',
            name='department',
            field=models.CharField(default='CS', max_length=100),
        ),
    ]
