# Generated by Django 4.2.3 on 2023-11-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0008_remove_studentmasterlist_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmasterlist',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='studentmasterlist',
            name='aps_01',
        ),
        migrations.RemoveField(
            model_name='studentmasterlist',
            name='aps_02',
        ),
        migrations.RemoveField(
            model_name='studentmasterlist',
            name='aps_03',
        ),
        migrations.RemoveField(
            model_name='studentmasterlist',
            name='department',
        ),
        migrations.RemoveField(
            model_name='studentmasterlist',
            name='sps_01',
        ),
        migrations.RemoveField(
            model_name='studentmasterlist',
            name='sps_02',
        ),
        migrations.RemoveField(
            model_name='studentmasterlist',
            name='sps_03',
        ),
        migrations.RemoveField(
            model_name='studentmasterlist',
            name='supervisor_name',
        ),
        migrations.RemoveField(
            model_name='studentmasterlist',
            name='topic_approval_seminar',
        ),
    ]
