# Generated by Django 4.2.3 on 2023-11-04 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0009_remove_studentmasterlist_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmasterlist',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Homepage.student_cards'),
        ),
    ]
