# Generated by Django 4.2.3 on 2023-11-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0011_remove_studentmasterlist_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmasterlist',
            name='aps_04',
        ),
        migrations.RemoveField(
            model_name='studentmasterlist',
            name='aps_05',
        ),
        migrations.RemoveField(
            model_name='studentmasterlist',
            name='aps_06',
        ),
        migrations.RemoveField(
            model_name='studentmasterlist',
            name='coursework_completed',
        ),
        migrations.RemoveField(
            model_name='studentmasterlist',
            name='sps_04',
        ),
        migrations.RemoveField(
            model_name='studentmasterlist',
            name='sps_05',
        ),
        migrations.RemoveField(
            model_name='studentmasterlist',
            name='sps_06',
        ),
        migrations.RemoveField(
            model_name='studentmasterlist',
            name='title_of_thesis',
        ),
        migrations.AlterField(
            model_name='studentmasterlist',
            name='chairman',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentmasterlist',
            name='external_evaluator',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentmasterlist',
            name='internal_evaluator',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
