# Generated by Django 4.2.3 on 2023-11-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0017_eventnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('grant_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grant_provider', models.CharField(max_length=100)),
                ('grant_deadline', models.DateField()),
            ],
        ),
    ]
